In [1]:
import pandas as pd

class OperacionesDataFrame:
  def __init__(self, datos, columnas):
    self.df = pd.DataFrame(datos, columns=columnas)

  def mostrar_dataframe(self):
    return self.df

  def agregar_columna(self, nombre_columna, datos):
    self.df[nombre_columna] = datos
    return self.df


In [2]:
# Conjunto de datos
datos = [[1, "a", 10.0],
         [2, "b", 20.0],
         [3, "a", 30.0],
         [4, "b", 40.0],
         [5, "c", 50.0]]

# Lista columnas
columnas = ["id", "Salones", "Num Alumnos"]

nombre_columna = ["M", "I", "V", "Mx", "B"]



## Operaciones entre matrices

1. Suma de matrices

$$\begin{pmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{pmatrix} + \begin{pmatrix} b_{11} & b_{12} & \cdots & b_{1n} \\ b_{21} & b_{22} & \cdots & b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ b_{m1} & b_{m2} & \cdots & b_{mn} \end{pmatrix} = \begin{pmatrix} a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n} \\ a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn} \end{pmatrix}$$


2. Suma de vectores:
$$(a_1,a_2,\dots, a_n)+(b_1+b_2+\dots+b_n)=(a_1+b_1,\dots, a_n+b_n)$$

3. Multiplicación de matrices

$$\begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix} \times \begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{pmatrix} = \begin{pmatrix} a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\ a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22} \end{pmatrix} $$

In [3]:
# Vamos a escribir una matriz

import numpy as np

# Convirtiendo una lista de listas a una matriz
A = np.array([[1, 2, 3], [0, 2 ,1.5], [0, 0 , 1]])
B = np.array([[0,1,0], [1, 1, 1], [0.5, 0.5, 3]])

print(A+B)

[[1.  3.  3. ]
 [1.  3.  2.5]
 [0.5 0.5 4. ]]


In [4]:
# Vamos a escribir dos matrices de tamaño 2x2

M_1 = np.array([[3, 2], [4,1]])
M_2 = np.array([[7, 1], [6,8]])

print(M_1)

print(M_2)

[[3 2]
 [4 1]]
[[7 1]
 [6 8]]


In [5]:
M_1 @ M_2 # Multiplicación de matrices

array([[33, 19],
       [34, 12]])

In [6]:
np.matmul(M_1,M_2)

array([[33, 19],
       [34, 12]])

In [7]:
op1 = OperacionesDataFrame(datos, columnas)
op1.mostrar_dataframe()

id Salones  Num Alumnos
0   1       a         10.0
1   2       b         20.0
2   3       a         30.0
3   4       b         40.0
4   5       c         50.0

In [8]:
df2_agregar = op1.agregar_columna("Favoritos",  ["M", "I", "V", "Mx", "B"])
df2_agregar

id Salones  Num Alumnos Favoritos
0   1       a         10.0         M
1   2       b         20.0         I
2   3       a         30.0         V
3   4       b         40.0        Mx
4   5       c         50.0         B

In [9]:
df2_agregar.query("Salones == 'b'")

id Salones  Num Alumnos Favoritos
1   2       b         20.0         I
3   4       b         40.0        Mx

In [10]:
# Creamos una clase heredada

class OperacionesDataFrame2(OperacionesDataFrame):
    def mostrar_dataframe(self):
        """
        Devuelve el DataFrame completo.
        """
        return self.df

    def agregar_columna(self, nombre_columna, datos):
        """
        Agrega una nueva columna al DataFrame.

        Args:
        - nombre_columna (str): Nombre de la nueva columna.
        - datos (list): Lista de valores para la nueva columna.

        Returns:
        - DataFrame actualizado.
        """
        self.df[nombre_columna] = datos
        return self.df

    def filtros_renglones(self, condicion):
        """
        Filtra los renglones del DataFrame según una condición.

        Args:
        - condicion (str): Condición para filtrar los datos (similar a SQL WHERE).

        Returns:
        - DataFrame filtrado.
        """
        return self.df.query(condicion)